### ISSUE TITLE
Client.appointments.list() broken

### ISSUE THREAD

**Issue by jgadelange** [SuperSaaS/supersaas-python-api-client#8]
First of all #7 prevents filtering on schedule_id. After locally fixing this bug another bug follows. The response is not parsed correctly. The appointment api implementation tries to read `'bookings'` from an list and leads to an error.

The traceback:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "<python path>/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "<python path>/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "<python path>/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "<python path>/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "<project path>/supersaas_sync/management/commands/sync_booked.py", line 50, in handle
    print(self.client.appointments.list(schedule_id=supersaas_id))
  File "<python path>/lib/python2.7/site-packages/SuperSaaS/API/Appointments.py", line 47, in list
    return self.__map_slots_or_bookings(res)
  File "<python path>/lib/python2.7/site-packages/SuperSaaS/API/Appointments.py", line 140, in __map_slots_or_bookings
    return [Appointment(attributes) for attributes in obj.get('bookings', [])]
AttributeError: 'list' object has no attribute 'get'
```

**Comment by TertiumQuid** [comment]
Good spot! The API's appointments endpoint can return variously formatted JSON depending on the schedule type, and in this case wasn't being deserialized for the right payload. Fixed in 0.10.3. Thanks again.
